vcs-facade:
  vcs:
    gitlab:
      enabled: # envFile property
      host: # envFile property
      token: # envFile property
      health-check:
        repo: # envFile property
        rootCommit: 9320183f5d5f5868fdb82b36e3abd6f9d1424114
        lastRelease: 321d4908aef10bafa1488f9b053270acc29f3d78
        expectedCommits: 9320183f5d5f5868fdb82b36e3abd6f9d1424114,00cc61dd4c3eca64d12e6beceff1a40a436962f5
    bitbucket:
      enabled: # envFile property
      host: # envFile property
      token: # envFile property
      health-check:
        repo: # envFile property
        rootCommit: 9320183f5d5f5868fdb82b36e3abd6f9d1424114
        lastRelease: 321d4908aef10bafa1488f9b053270acc29f3d78
        expectedCommits: 9320183f5d5f5868fdb82b36e3abd6f9d1424114,00cc61dd4c3eca64d12e6beceff1a40a436962f5
    gitea:
      enabled: # envFile property
      host: # envFile property
      token: # envFile property
      health-check:
        repo: # envFile property
        rootCommit: 9320183f5d5f5868fdb82b36e3abd6f9d1424114
        lastRelease: 321d4908aef10bafa1488f9b053270acc29f3d78
        expectedCommits: 9320183f5d5f5868fdb82b36e3abd6f9d1424114,00cc61dd4c3eca64d12e6beceff1a40a436962f5
  job:
    executor:
      corePoolSize: 4
      maxPoolSize: 10
      queueCapacity: 500
    fast-work-timout-secs: 0
    retry-interval-secs: 1

opensearch:
  uris: # envFile property
  username: # envFile property
  password: # envFile property
  index:
    suffix: dev

logging:
  level:
    org.octopusden.octopus.vcsfacade.controller: trace
