vcs-facade:
  vcs:
    bitbucket:
      enabled: # envFile property
      host: # envFile property
      token: # envFile property
      health-check:
        repo: # envFile property
        root-commit: 9320183f5d5f5868fdb82b36e3abd6f9d1424114
        last-release: 321d4908aef10bafa1488f9b053270acc29f3d78
        expected-commits: 9320183f5d5f5868fdb82b36e3abd6f9d1424114,00cc61dd4c3eca64d12e6beceff1a40a436962f5
    gitea:
      enabled: # envFile property
      host: # envFile property
      token: # envFile property
      health-check:
        repo: # envFile property
        root-commit: 9320183f5d5f5868fdb82b36e3abd6f9d1424114
        last-release: 321d4908aef10bafa1488f9b053270acc29f3d78
        expected-commits: 9320183f5d5f5868fdb82b36e3abd6f9d1424114,00cc61dd4c3eca64d12e6beceff1a40a436962f5
    gitlab:
      enabled: # envFile property
      host: # envFile property
      token: # envFile property
      health-check:
        repo: # envFile property
        root-commit: 9320183f5d5f5868fdb82b36e3abd6f9d1424114
        last-release: 321d4908aef10bafa1488f9b053270acc29f3d78
        expected-commits: 9320183f5d5f5868fdb82b36e3abd6f9d1424114,00cc61dd4c3eca64d12e6beceff1a40a436962f5
  job:
    executor:
      core-pool-size: 4
      max-pool-size: 10
      queue-capacity: 500
    fast-work-timout-secs: 0
    retry-interval-secs: 1

opensearch:
  host: # envFile property
  ssl: # envFile property
  username: # envFile property
  password: # envFile property
  index:
    suffix: dev

logging:
  level:
    org.octopusden.octopus.vcsfacade: debug

management:
  endpoints:
    web:
      exposure:
        # curl -i -X POST -H 'Content-Type: application/json' -d '{"configuredLevel": "INFO"}' http://localhost:8080/actuator/loggers/ROOT
        include: health, env, metrics, threaddump, heapdump, info, configprops, prometheus, loggers
