vcs-facade:
  vcs:
    services:
      - id: dev-vcs-service
        type: ${VCS_FACADE_VCS_TYPE}
        http-url: ${VCS_FACADE_VCS_HTTP_URL}
        ssh-url: ${VCS_FACADE_VCS_SSH_URL}
        token: ${VCS_FACADE_VCS_TOKEN}
  job:
    fast-work-timout-secs: 0
    retry-interval-secs: 1
    executor:
      core-pool-size: 4
      max-pool-size: 10
      queue-capacity: 500
      pre-start-all-core-threads: true
  opensearch:
    enabled: ${VCS_FACADE_OPENSEARCH_ENABLED:false}
    host: ${VCS_FACADE_OPENSEARCH_HOST:}
    ssl: ${VCS_FACADE_OPENSEARCH_SSL:false}
    username: ${VCS_FACADE_OPENSEARCH_USERNAME:}
    password: ${VCS_FACADE_OPENSEARCH_PASSWORD:}
    index:
      suffix: dev
      scan:
        cron: "-"
        delay: 60000
        executor:
          core-pool-size: 1
          max-pool-size: 1
          queue-capacity: 10
          pre-start-all-core-threads: true

logging:
  level:
    org.octopusden.octopus.vcsfacade: trace

management:
  endpoints:
    web:
      exposure:
        # curl -i -X POST -H 'Content-Type: application/json' -d '{"configuredLevel": "INFO"}' http://localhost:8080/actuator/loggers/ROOT
        include: health, env, metrics, threaddump, heapdump, info, configprops, prometheus, loggers
