{{- if eq .Values.mode "ft" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "vcsFacade.fullname" . }}-route
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: {{ template "vcsFacade.fullname" . }}
{{- end }}