version: '2.4'

services:
  vcs-facade:
    container_name: vcs-facade-ft-vcs-facade
    image: ${OCTOPUS_GITHUB_DOCKER_REGISTRY}/octopusden/vcs-facade:${VCS_FACADE_VERSION}
    depends_on:
      bitbucket:
        condition: service_started
    ports:
      - "8080:8080"
    volumes:
      - ./application-bitbucket.yml:/application-bitbucket.yml
      - ./../application-ft.yml:/application-ft.yml
      - ./../bootstrap-ft.yml:/bootstrap-ft.yml
    environment:
      - SPRING_CONFIG_ADDITIONAL_LOCATION=/
      - SPRING_PROFILES_ACTIVE=ft,bitbucket

  bitbucket:
    container_name: vcs-facade-ft-bitbucket
    image: ${DOCKER_REGISTRY}/atlassian/bitbucket-server:${BITBUCKET_VERSION}
    depends_on:
      bitbucket-db:
        condition: service_started
    ports:
      - "7999:7999"
      - "7990:7990"
    environment:
      SETUP_DISPLAYNAME: Bitbucket
      SETUP_BASEURL: http://bitbucket:7990
      SETUP_LICENSE: ${BITBUCKET_LICENSE}
      SETUP_SYSADMIN_USERNAME: admin
      SETUP_SYSADMIN_PASSWORD: admin
      SETUP_SYSADMIN_DISPLAYNAME: Dev Instance Admin
      SETUP_SYSADMIN_EMAILADDRESS: admin@domain.corp
      JDBC_DRIVER: org.postgresql.Driver
      JDBC_USER: bitbucket
      JDBC_PASSWORD: bitbucket
      JDBC_URL: jdbc:postgresql://bitbucket-db:5432/bitbucket

  bitbucket-db:
    container_name: vcs-facade-ft-bitbucket-db
    image: ${DOCKER_REGISTRY}/postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_USER: bitbucket
      POSTGRES_PASSWORD: bitbucket
      POSTGRES_DB: bitbucket
