version: '2.4'

services:
  gitlab:
    container_name: vcs-facade-ut-gitlab
    image: ${DOCKER_REGISTRY}/gitlab/gitlab-ce:${GITLAB_VERSION}
    depends_on:
      gitlab-db:
        condition: service_started
    ports:
      - "8990:8990"
    volumes:
      - ./gitlab.rb:/etc/gitlab/gitlab.rb

  gitlab-db:
    container_name: vcs-facade-ut-gitlab-db
    image: ${DOCKER_REGISTRY}/postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: gitlab
      POSTGRES_DB: gitlab
