apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: test-vcs-facade
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ${DEPLOYMENT_PREFIX}-vcs-facade-config
    data:
      application-dev.yml: |-
        ${APPLICATION_DEV_CONTENT}
      application-bitbucket.yml: |-
        ${APPLICATION_BITBUCKET_CONTENT}
      application-gitea.yml: |-
        ${APPLICATION_GITEA_CONTENT}
  - apiVersion: v1
    kind: Pod
    metadata:
      name: ${DEPLOYMENT_PREFIX}-vcs-facade
      labels:
        app.kubernetes.io/name: ${DEPLOYMENT_PREFIX}-vcs-facade
    spec:
      restartPolicy: Never
      activeDeadlineSeconds: ${{ACTIVE_DEADLINE_SECONDS}}
      containers:
        - name: vcs-facade
          image: ${DOCKER_REGISTRY}/octopusden/vcs-facade:${VCS_FACADE_IMAGE_TAG}
          imagePullPolicy: Always
          env:
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: /app/config/
            - name: SPRING_PROFILES_ACTIVE
              value: dev,${VCS_FACADE_VCS_TYPE}
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "false"
            - name: VCS_FACADE_OPENSEARCH_HOST
              value: ${VCS_FACADE_OPENSEARCH_HOST}
            - name: VCS_FACADE_VCS_HOST
              value: ${VCS_FACADE_VCS_HOST}
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 10
          volumeMounts:
            - mountPath: /app/config/
              name: vcs-facade-config
      volumes:
        - name: vcs-facade-config
          configMap:
            name: ${DEPLOYMENT_PREFIX}-vcs-facade-config
            items:
              - key: application-dev.yml
                path: application-dev.yml
              - key: application-bitbucket.yml
                path: application-bitbucket.yml
              - key: application-gitea.yml
                path: application-gitea.yml
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${DEPLOYMENT_PREFIX}-vcs-facade-service
    spec:
      ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app.kubernetes.io/name: ${DEPLOYMENT_PREFIX}-vcs-facade
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: ${DEPLOYMENT_PREFIX}-vcs-facade-route
    spec:
      port:
        targetPort: 8080
      to:
        kind: Service
        name: ${DEPLOYMENT_PREFIX}-vcs-facade-service

parameters:
  - description: Unique deployment prefix
    name: DEPLOYMENT_PREFIX
    required: true
  - description: Active deadline seconds
    name: ACTIVE_DEADLINE_SECONDS
    required: true
  - description: Docker registry
    name: DOCKER_REGISTRY
    required: true
  - description: Tag of octopusden/vcs-facade image
    name: VCS_FACADE_IMAGE_TAG
    required: true
  - description: VCS type (bitbucket/gitea)
    name: VCS_FACADE_VCS_TYPE
    required: true
  - description: VCS host
    name: VCS_FACADE_VCS_HOST
    required: true
  - description: Opensearch host
    name: VCS_FACADE_OPENSEARCH_HOST
    required: true
  - description: application-dev.yml content
    name: APPLICATION_DEV_CONTENT
    required: true
  - description: application-bitbucket.yml content
    name: APPLICATION_BITBUCKET_CONTENT
    required: true
  - description: application-gitea.yml content
    name: APPLICATION_GITEA_CONTENT
    required: true
