vcs-facade:
  job:
    executor:
      core-pool-size: 4
      max-pool-size: 10
      queue-capacity: 500
    fast-work-timout-secs: 0
    retry-interval-secs: 1

logging:
  level:
    org.octopusden.octopus.vcsfacade: trace
