version: '3'

services:
  vcs-facade:
    container_name: vcs-facade-ft-vcs-facade
    image: ${OCTOPUS_GITHUB_DOCKER_REGISTRY}/octopusden/vcs-facade:${APP_VERSION:-1.0-SNAPSHOT}
    depends_on:
      - gitlab
      - bitbucket
    ports:
      - "8080:8080"
    volumes:
      - ./application-ft.yml:/application-ft.yml
      - ./bootstrap-ft.yml:/bootstrap-ft.yml
    environment:
      - SPRING_CONFIG_ADDITIONAL_LOCATION=/
      - SPRING_PROFILES_ACTIVE=ft

  bitbucket:
    container_name: vcs-facade-ft-bitbucket
    image: ${DOCKER_REGISTRY}/atlassian/bitbucket-server:8.13.0-jdk11
    depends_on:
      - bitbucket-db
    ports:
      - "7999:7999"
      - "7990:7990"
    environment:
      SETUP_DISPLAYNAME: Bitbucket
      SETUP_BASEURL: http://bitbucket:7990
      SETUP_LICENSE: ${BITBUCKET_LICENSE}
      SETUP_SYSADMIN_USERNAME: admin
      SETUP_SYSADMIN_PASSWORD: admin
      SETUP_SYSADMIN_DISPLAYNAME: Dev Instance Admin
      SETUP_SYSADMIN_EMAILADDRESS: admin@domain.corp
      JDBC_DRIVER: org.postgresql.Driver
      JDBC_USER: bitbucket
      JDBC_PASSWORD: bitbucket
      JDBC_URL: jdbc:postgresql://bitbucket-db:5432/bitbucket

  bitbucket-db:
    container_name: vcs-facade-ft-bitbucket-db
    image: ${DOCKER_REGISTRY}/postgres:13-alpine
    environment:
      POSTGRES_USER: bitbucket
      POSTGRES_PASSWORD: bitbucket
      POSTGRES_DB: bitbucket

  gitlab:
    container_name: vcs-facade-ft-gitlab
    image: ${DOCKER_REGISTRY}/gitlab/gitlab-ce:16.2.4-ce.0
    depends_on:
      - gitlab-db
    ports:
      - "8990:8990"
    volumes:
      - ./gitlab/gitlab.rb:/etc/gitlab/gitlab.rb

  gitea:
    image: ${DOCKER_REGISTRY}/gitea/gitea:1.20.4
    container_name: vcs-facade-ft-gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - ./gitea/app.ini:/data/gitea/conf/app.ini
      - ./gitea/add_admin.sh:/tmp/add_admin.sh
    ports:
      - "3000:3000"
      - "222:22"

  gitlab-db:
    container_name: vcs-facade-ft-gitlab-db
    image: ${DOCKER_REGISTRY}/postgres:13-alpine
    environment:
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: gitlab
      POSTGRES_DB: gitlab
    ports:
      - "6432:5432"
