version: '3'

services:
  vcs-facade:
    container_name: ft-vcs-facade
    image: ${OCTOPUS_GITHUB_DOCKER_REGISTRY}/octopusden/vcs-facade:${APP_VERSION:-1.0-SNAPSHOT}
    ports:
      - "8080:8080"
    volumes:
      - ./application-ft.yml:/application-ft.yml
      - ./bootstrap-ft.yml:/bootstrap-ft.yml
    environment:
      - SPRING_CONFIG_ADDITIONAL_LOCATION=/
      - SPRING_PROFILES_ACTIVE=ft

  bitbucket:
    container_name: ft-bitbucket
    image: ${DOCKER_REGISTRY}/atlassian/bitbucket-server:8.6.1-jdk11
    ports:
      - "7999:7999"
      - "7990:7990"
    environment:
      SETUP_DISPLAYNAME: Bitbucket
      SETUP_BASEURL: http://bitbucket:7990
      SETUP_LICENSE: ${BITBUCKET_LICENSE}
      SETUP_SYSADMIN_USERNAME: admin
      SETUP_SYSADMIN_PASSWORD: admin
      SETUP_SYSADMIN_DISPLAYNAME: Dev Instance Admin
      SETUP_SYSADMIN_EMAILADDRESS: admin@domain.corp
      JDBC_DRIVER: org.postgresql.Driver
      JDBC_USER: bitbucket
      JDBC_PASSWORD: bitbucket
      JDBC_URL: jdbc:postgresql://bitbucket-db:5432/bitbucket

  bitbucket-db:
    container_name: ft-bitbucket-db
    image: ${DOCKER_REGISTRY}/postgres:12-alpine
    environment:
      POSTGRES_USER: bitbucket
      POSTGRES_PASSWORD: bitbucket
      POSTGRES_DB: bitbucket

  mockserver:
    container_name: ft-mockserver
    image: ${DOCKER_REGISTRY}/mockserver/mockserver:mockserver-5.11.1
    ports:
      - "1080:1080"
