version: '3'

services:
  vcs-facade:
    container_name: vcs-facade-ft-vcs-facade
    image: ${OCTOPUS_GITHUB_DOCKER_REGISTRY}/octopusden/vcs-facade:${VCS_FACADE_VERSION}
    depends_on:
      gitlab:
        condition: service_started
    ports:
      - "8080:8080"
    volumes:
      - ./application-gitlab.yml:/application-gitlab.yml
      - ./../application-ft.yml:/application-ft.yml
      - ./../bootstrap-ft.yml:/bootstrap-ft.yml
    environment:
      - SPRING_CONFIG_ADDITIONAL_LOCATION=/
      - SPRING_PROFILES_ACTIVE=ft,gitlab

  gitlab:
    container_name: vcs-facade-ft-gitlab
    image: ${DOCKER_REGISTRY}/gitlab/gitlab-ce:${GITLAB_VERSION}
    depends_on:
      gitlab-db:
        condition: service_started
    ports:
      - "8990:8990"
    volumes:
      - ./gitlab.rb:/etc/gitlab/gitlab.rb

  gitlab-db:
    container_name: vcs-facade-ft-gitlab-db
    image: ${DOCKER_REGISTRY}/postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: gitlab
      POSTGRES_DB: gitlab
    ports:
      - "6432:5432"
