name: Gradle Release

on:
  repository_dispatch:
    types: release

jobs:
  build:
    uses: octopusden/octopus-base/.github/workflows/common-java-gradle-release.yml@v2.1.7
    with:
      flow-type: hybrid
      java-version: '17'
      commit-hash: ${{ github.event.client_payload.commit }}
      build-version: ${{ github.event.client_payload.project_version }}
      docker-image: vcs-facade
    secrets: inherit
